# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页 | Home
    url: /
    weight: 10
  - name: 发表文章 | Publications
    url: /publication/
    weight: 20
  - name: 项目 | Projects
    url: projects/
    weight: 30
  - name: 经历 | Experience
    url: experience/
    weight: 40
  - name: 教学 | Teaching
    url: teaching/
    weight: 45
    hasChildren: true
  - name: 实验室仪器 | Instruments
    url: /teaching/laboratory-instruments/
    parent: teaching/
    weight: 46
  - name: 实验教程 | Tutorials
    url: /teaching/tutorials/
    parent: teaching/
    weight: 47
  - name: 研究视频 | Videos
    url: videos/
    weight: 50
